### ISSUE TITLE
Subnet warning incorrect.

### ISSUE THREAD

**Issue by individualist** [JPersson77/LGTVCompanion#152]
For some subnets, even though the TV and PC are on the same subnet - LGTV Companion warns that they are not. 

Here's an example:

```
PC is 10.10.18.1/22
LGTV is 10.10.19.200/22
```

For the above subnet:
```
Network Address/CIDR: 10.10.16.0/22
Subnet Mask: 255.255.252.0
Valid Host IP rage: 10.10.16.1 - 10.10.19.254
Broadcast Address: 10.10.19.255
```

I don't know if it's related or not, but scan has never worked for me in such a configuration either. Manual configuration seems to work fine though.

**Comment by JPersson77** [comment]
Hi @individualist , thanks for the bug report. I will review the code

**Comment by JPersson77** [comment]
This should be fixed in v3.1.9, Issue closed

**Comment by individualist** [comment]
Hi, @JPersson77 
Unfortunately this is still happening for me for subnet 255.255.252.0 (22)

I could be mistaken, but I think the issue may be that during the conversion, the CIDR is being incremented on all bits, but should only increment for bits that are on...

https://github.com/JPersson77/LGTVCompanion/blob/83073254c70344adb692f335fcff47db902ccb53/Common/Common.cpp#L152-L155

e.g.
```
if ((m & 0x01) == 0x01) CIDR++
```

This seems to produce CIDR=22, as I expected. Otherwise it produces CIDR=24. 

As an aside, this tool is great, thanks for creating it: it really increases quality of life when using a LG OLED.

**Comment by JPersson77** [comment]
Thanks! Appreciate the detailed response again. Reopening the issue to try again

**Comment by JPersson77** [comment]
Should be fixed in the next version. Please confirm

**Comment by JPersson77** [comment]
Closing due to inactivity. Please feel free to reopen as needed
