### ISSUE TITLE
TV turns off but not back on again with latest firmware

### ISSUE THREAD

**Issue by sesquipedality** [JPersson77/LGTVCompanion#6]
Hello,

The companion app was working fine on my LG OLED55CX5LB until recent firmware upgrades.  I am now on 03.23.06.   Here is the relevant log extract:

Wed 15:22:42 > ** System resumed from low power state.
Wed 15:22:46 > Device1, WARNING! DisplayPowerOnThread(): connect: A socket operation was attempted to an unreachable host
Wed 15:22:52 > Device1, WARNING! DisplayPowerOnThread(): connect: A socket operation was attempted to an unreachable host
Wed 15:23:13 > Device1, response received: {"type":"registered","id":"register_0","payload":{"client-key":"e1bf163e389129cf459b96b761e4cd48"}}
Wed 15:23:13 > Device1, established contact: Display is powered ON.  
Wed 15:23:14 > Device1, repeating WOL broadcast ended

Please note that I powered on the monitor manually.

Running LGTV Companion 1.2.0 under Windows 10 21H1.

TV is connected via wired LAN.

Can you help, please?

**Comment by sesquipedality** [comment]
Confirmed the same issue is present with 1.3.0 .  Here is the log of a test run from the app.  Again, I turned the TV on myself at the end.

Wed 15:37:03 > IPC command received: -poweroff Device1
Wed 15:37:03 > Device1, spawning DisplayPowerOffThread().
Wed 15:37:03 > Device1, established contact: Display is powered OFF.  
Wed 15:37:14 > IPC command received: -poweron Device1
Wed 15:37:14 > Device1, spawning DisplayPowerOnThread().
Wed 15:37:14 > Device1, repeating WOL broadcast started to MAC: 58:FD:B1:DB:02:F8
Wed 15:37:30 > Device1, response received: {"type":"registered","id":"register_0","payload":{"client-key":"e1bf163e389129cf459b96b761e4cd48"}}
Wed 15:37:30 > Device1, established contact: Display is powered ON.  
Wed 15:37:30 > Device1, repeating WOL broadcast ended

**Comment by JPersson77** [comment]
Hi there,

i had another report of the same issue. Cannot confirm it myself, but let's try to fix it.

Is your TV/PC connected via wifi or wire? Do you have more than one network interfaces on your PC? Can you confirm that the TV and PC is on the same subnet/VLAN?

Also, I'd like the full log please, there should be some more tidbits earlier on regarding the host interface(s).

Cheers and thanks for the report

**Comment by sesquipedality** [comment]
Just on the off chance I added in the wireless MAC address as well.  I didn't expect this to help as the wireless interface isn't in use, and indeed it didn't.   Here's the logs though as it contains slightly more useful info as I waited longer before turning the screen back on again.

Wed 16:00:29 > IPC command received: -poweron Device1
Wed 16:00:29 > Device1, spawning DisplayPowerOnThread().
Wed 16:00:29 > Device1, repeating WOL broadcast started to MAC: 58:FD:B1:DB:02:F8
Wed 16:00:29 > Device1, repeating WOL broadcast started to MAC: AC:F1:08:EC:3C:D0
Wed 16:00:51 > Device1, WARNING! DisplayPowerOnThread(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Wed 16:00:54 > Device1, response received: {"type":"registered","id":"register_0","payload":{"client-key":"e1bf163e389129cf459b96b761e4cd48"}}
Wed 16:00:54 > Device1, established contact: Display is powered ON.  
Wed 16:00:56 > Device1, repeating WOL broadcast ended

**Comment by JPersson77** [comment]
Thanks again, I see now that the TV is wired. Can you please have a look at the other questions too in my previous comment.

**Comment by JPersson77** [comment]
Also, can you confirm that "Turn on via Wi-Fi(Networked standby mode)" is still enabled under options/Connection/Mobile connection management please.

**Comment by sesquipedality** [comment]
I do have two wired interfaces and a wireless interface on my PC.  Only one is connected.

TV and PC are on the same LAN subnet and not on a VPN.

Log attached here.

[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/6625394/Log.txt)
[](url)

Wifi standby mode is enabled, although it is under "Connection -> Mobile Connection Management -> TV on with Mobile -> Turn on via WiFI (Networked Standby Mode)" on my interface.

Thanks

**Comment by JPersson77** [comment]
Thanks, I think I might have a fix potentially. I'll patch the code when I have a little free time and maybe you can test drive before publishing?

**Comment by sesquipedality** [comment]
Thanks.  Let me know when it's done and I will happily test.

**Comment by JPersson77** [comment]
Hi again, please check this version out: https://drive.google.com/file/d/1yp_QGdza5sRAY7Hp_7wePZjhKh0B3yVB/view?usp=sharing

Once installed, please reconfigure the network options per device/TV and select to "send wol broadcasts using the device IP and subnet mask". You may have to configure the subnet mask accordingly in the options as well, but I guess you know if you need to do this. If you want to double check you can use f.e. the IPCONFIG command in the command prompt to check the subnet masks for the subnets the PC's network interfaces are connected to.

Fingers crossed

https://drive.google.com/file/d/1yp_QGdza5sRAY7Hp_7wePZjhKh0B3yVB/view?usp=sharing

**Comment by JPersson77** [comment]
I published v.1.4.0 which contains the additional feature / fix. Let me know if it works for you please :)

**Comment by JPersson77** [comment]
Closing this issue due to missing feedback, but I think it is fixed. Let me know if you still have the issue and I will reopen. Cheers!

**Comment by sesquipedality** [comment]
Unfortunately I think the feedback may have been eaten by spam filters, or something.  Unfortunately it's still not fixed.   Text of emails below:

- - -
Sending to the IP address works (Yay!) sending to the subnet does not. Log attached. (Entered the wrong subnet mask on the first two attempts due to early morning brain confusion, but the last couple of failures are with the correct subnet mask set.)

I'll leave it set to send to IP for now, but if you need me to test an update, let me know.
- - -
I'm afraid I spoke too soon.  Although "send to IP" works in test mode, it does not work when actually resuming from a low power state.  Log attached. 
- - -
Re r1.4.0

No, sorry, same issue.  Subnet doesn't work in test mode.  IP address works in test mode, but not when resuming from sleep.
- - -

I will attach the latest logs.
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/6716369/Log.txt)

**Comment by JPersson77** [comment]
Hi again,
 yeah looks like those replies were lost in space. I think it should be preferred to use the third WOL option (using the subnet mask and the broadcast address 192.168.37.255) so let's try to troubleshoot some more. The second option to send to IP is not preferred as there might be routing table issues after the TV has been powered off for a while. The log conflicts with your report a bit so let's try to sort it out first. From reading the log I can see that the TV actually seem to respond to the power on commands. Take for example this part:

`Sun 01:02:10 > IPC command received: -poweroff Device1
Sun 01:02:10 > Device1, spawning DisplayPowerOffThread().
Sun 01:02:11 > Device1, established contact: Display is powered OFF.  
Sun 01:02:14 > IPC command received: -poweron Device1
Sun 01:02:14 > Device1, spawning DisplayPowerOnThread().
Sun 01:02:14 > Device1, repeating WOL broadcast started to MAC: 58:FD:B1:DB:02:F8 using broadcast address: 192.168.37.255
Sun 01:02:14 > Device1, repeating WOL broadcast started to MAC: AC:F1:08:EC:3C:D0 using broadcast address: 192.168.37.255
Sun 01:02:14 > Device1, response received: {"type":"registered","id":"register_0","payload":{"client-key":"e1bf163e389129cf459b96b761e4cd48"}}
Sun 01:02:14 > Device1, established contact: Display is powered ON.  `

For the above log extract you had configured the app using the third WOL-option and the WOL was therefore sent to broadcast adress 192.168.37.255 which should be correct. Unless you manually powered on the TV between time 01:02:11 and 01:02:14 it looks, from reading the log, like the TV was actually powered on. But you say that the TV wasn't powered which is of course troublesome. The logical conclusion from that is that the TV chose to respond to the query (in the log this is ""type":"registered","id":"register_0","payload":{"client-key":"e1bf163e389129cf459b96b761e4cd48"}" from the LGTV companion app, even though it did not actually wake up and show the output from the graphics card. Does that sound correct to you or am I misreading the log? 

If the screen is running a pixel refresh the above behaviour could potentially be observed (I've heard, but not experienced myself). However, even if that was the case, the screen should not be running a pixel refresh very often. In essence I currently don't understand why this behaviour is observed (if the observation is correct) and for reference I have also CX TVs (one 48 and one 65), both are on the same firmware version as you, and both works well. 

Can you try to use this program to see if you can wake the TV with it: https://wol.aquilatech.com/ , specifically using the broadcast address 192.168.37.255 and then let me know how that goes. This program should help you understand if the TV can actually be woken or not using WOL, and it can also be used to listen for magic packets which you can use to confirm that your router correctly broadcast the WOL on the subnet. Let me know if you need further help with using the app.

Maybe check also that "Quickstart+" is enabled and disable "HDD Eco mode". This is sometimes needed for wireless NICs to not become inactive, but try it anyway even though you have a wired connection.

Maybe send me an email adress I can contact you via as well, if that would be OK with you. Might be more efficient to communicate via email. Remember to obfuscate it a bit so the email adress isn't picked up by email harvesting bots.

Cheers!

**Comment by sesquipedality** [comment]
<name of this github account>@gmail.com will work.

Quickstart+ is enabled.  I have turned off HDD Eco Mode, but this doesn't seem to effect wake by broadcast address at all (i.e. still not working even in test mode).  I don't have an HDD attached to the TV so that's perhaps not too surprising.

I can confirm I am able to use AquilaTech Wake on Lan to wake the TV, but it requires me to enter the IP and MAC address before it will save, so I have no idea whether it's using the broadcast IP or sending direct to the entered IP.

**Comment by sesquipedality** [comment]
OK, using the WakeOnLan listener, I can see that WakeOnLan is broadcasting to <subnet>.255.  LGTV Companion is sending the broadcasts to 255.255.255.255 i.e. it seems to be ignoring the subnet mask setting.

**Comment by sesquipedality** [comment]
OK, so looking more closely at these messages, they are being broadcast from the IP of the  Hyper-V Virtual Ethernet Adapter.   I am not sure that that adapter is doing, as I don't think I am running anything under Hyper-V, but that is definitely the wrong interface to be sending out the WOL packets on.

**Comment by JPersson77** [comment]
Hi again, I sent a link to a test version to your email account.

**Comment by JPersson77** [comment]
v1.4.2 is the patched version and work according to feedback from sequipedality. Thanks for reporting the bug.
